version: '3'
services:
  order-service:
    build:
      context: ./order-service/
      args:
        baseImageVersion: ${EVENTUATE_JAVA_BASE_IMAGE_VERSION}
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./build/libs:/app
    depends_on:
      - mssql
      - kafka
      - zookeeper
      - cdc-service
    environment:
      EVENTUATEDATABASE: mssql
      QUARKUS_DATASOURCE_USERNAME: sa
      QUARKUS_DATASOURCE_PASSWORD: Eventuate123!
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:sqlserver://mssql:1433;databaseName=eventuate
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  customer-service:
    build:
      context: ./customer-service/
      args:
        baseImageVersion: ${EVENTUATE_JAVA_BASE_IMAGE_VERSION}
    restart: always
    ports:
      - "8082:8080"
    volumes:
      - ./build/libs:/app
    depends_on:
      - mssql
      - kafka
      - zookeeper
      - cdc-service
    environment:
      EVENTUATEDATABASE: mssql
      QUARKUS_DATASOURCE_USERNAME: sa
      QUARKUS_DATASOURCE_PASSWORD: Eventuate123!
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:sqlserver://mssql:1433;databaseName=eventuate
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  order-history-service:
    build:
      context: ./order-history-service/
      args:
        baseImageVersion: ${EVENTUATE_JAVA_BASE_IMAGE_VERSION}
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - mongodb
      - kafka
      - zookeeper
      - cdc-service
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      QUARKUS_MONGODB_CONNECTION_STRING: mongodb://mongodb:27017/customers_and_orders

  zookeeper:
    image: eventuateio/eventuate-zookeeper:$EVENTUATE_COMMON_VERSION
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_HEAP_OPTS: -Xmx64m

  kafka:
    image: "eventuateio/eventuate-kafka:$EVENTUATE_MESSAGING_KAFKA_IMAGE_VERSION"
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: -Xmx192m


  mssql:
    image: eventuateio/eventuate-mssql:$EVENTUATE_COMMON_VERSION
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: Eventuate123!
      ACCEPT_EULA: Y

  mongodb:
    image: mongo:4.2.12
    hostname: mongodb
    ports:
      - "27017:27017"

  cdc-service:
    image: eventuateio/eventuate-cdc-service:$EVENTUATE_CDC_VERSION
    ports:
      - "8099:8080"
    depends_on:
      - mssql
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql:1433;databaseName=eventuate
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: Eventuate123!
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.microsoft.sqlserver.jdbc.SQLServerDriver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_READER_NAME: MsSqlReader
      EVENTUATE_OUTBOX_ID: 1
      SPRING_PROFILES_ACTIVE: mssql,EventuatePolling
      JAVA_OPTS: -Xmx64m